algoritmo "ConversordeMoedas"
var
   C, Q: inteiro
   R, D: real
inicio
      C <- 1]
      escreva ("Quantas vezes você quer converter? ")
      leia (Q)
      enquanto (C <= Q) faca
               escreva ("Quantos reais eu tenho? R$")
               leia (R)
               D <- R/6,15
               escreval ("Posso ter US$", D:5:2)
               C <- C + 1
      fimenquanto
fimalgoritmo